package com.datafundamentals.xprmnt;

import org.apache.camel.builder.RouteBuilder;

/**
 * A Camel Java DSL Router - generated by Pete Carapetyan via 'Carrie' UI
 */
public class MyRouteBuilder extends RouteBuilder {
     
    public void configure() {
        from("file:src/data/toftp?noop=true")
        .to("sftp://cloudera@192.168.2.63:/Documents?password=cloudera");
        from("timer:foo?period=10000")
        .setBody(constant("./dothis.sh"))
        .to("ssh://cloudera@192.168.2.63?password=cloudera&useFixedDelay=true&delay=5000")
        .to("log:org.apache.camel.builder.MyRouteBuilder?showAll=true&multiline=true");
    }
}
