/*
Copyright 2014 John Smith

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 
This file generated by John Smith via 'Carrie' UI
 */


package com.datafundamentals.refactorme;

import org.apache.camel.builder.RouteBuilder;

/**
 * A Camel Java DSL Router - generated by John Smith via 'Carrie' UI
 */
public class MyRouteBuilder extends RouteBuilder {
     
    public void configure() {
    	// move any data files which appear in the ETL folder to processing folder
        from("file:~/work/etldrop/abcdefg?noop=true")
		.to("avroetl:abar?outputFilePath=target/output/testResults&delimiter=,&exceptionOnBadData=false&className=FooBar&namespace=org.foo.bar")
        .to("sftp://root@127.0.0.1://my/dir/abcdefg?password=hadoop");	
        
        // move the program files too - these should only move first time, after that this should not have any effect
        from("file:bin?noop=true")
        .to("sftp://root@127.0.0.1://my/dir/abcdefg?password=hadoop");
        
        // run hive commands to inject data from the hadoop vm into the hive tables
        from("timer:foo?period=10000")
        .setBody(constant("./runhive.sh"))
        .to("ssh://root@127.0.0.1?password=hadoop&useFixedDelay=true&delay=5000")
        .to("log:org.apache.camel.builder.MyRouteBuilder?showAll=true&multiline=true");
    }
}
