/*
Copyright 2014 Carrie White

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 
This file generated by Carrie White via 'Carrie' UI
 */


package com.datafundamentals.refactorme;

import org.apache.camel.builder.RouteBuilder;

/**
 * A Camel Java DSL Router - generated by Carrie White via 'Carrie' UI
 */
public class MyRouteBuilder extends RouteBuilder {
     
    public void configure() {

// copy any data files which appear in the ETL drop folder to processing folder to run toAvro
        from("file:work/etldrop/abcdefg?noop=true")
        .log("copied file for avro transformation: ${in.header.CamelFileName}")
		.to("file:work/etldrop/abcdefg/transform");

// run toAvro and create new avro files
        from("file:work/etldrop/abcdefg/transform?include=.*.csv")
        .log("toAvro transformation: ${in.header.CamelFileName}")
		.to("avroetl:abar?outputFilePath=work/etldrop/abcdefg/transform/test1&delimiter=,&exceptionOnBadData=false&className=BarFoo&namespace=org.foo.bar");
		
//now, move newly created avro files back to ETL drop folder
//        from("file:work/etldrop/abcdefg/transform")
//        .log("moved file after avro transformation: ${in.header.CamelFileName}")
//        .to("sftp://root@127.0.0.1:2222//my/dir/abcdefg?password=hadoop");	

//copy all files to the hadoop server input folder
//        from("file:work/etldrop/abcdefg?noop=true")
//        .log("copied all files to server: ${in.header.CamelFileName}")
//        .to("sftp://root@127.0.0.1://my/dir/abcdefg?password=hadoop");	
        
// move the program files too - these should only move first time, after that this should not have any effect
//        from("file:bin?noop=true")
//        .to("sftp://root@127.0.0.1://my/dir/abcdefg?password=hadoop");
        
// run hive commands to inject data from the hadoop vm into the hive tables
//        from("timer:foo?period=10000")
//        .setBody(constant("./runhive.sh"))
//        .to("ssh://root@127.0.0.1?password=hadoop&useFixedDelay=true&delay=5000")
//        .to("log:org.apache.camel.builder.MyRouteBuilder?showAll=true&multiline=true");
    }
}
